# Aula 6 - Introdução ao Numpy
## Prof. Luis Lamas

Acompanhe os vídeos no canal do SMART Research Group:
https://www.youtube.com/channel/UCvV5eUanrGET9LWPB8jzWQw

Nessa aula vamos aprender a trabalhar com bibliotecas no python, e começar a utilizar a biblioteca numpy. A numpy é uma biblioteca especializada em operar vetores e matrizes, e é particularmente útil para programação científica.

https://numpy.org/

Para se instalar a biblioteca, utiliza-se o comando a seguir:


In [1]:
! pip install numpy

In [2]:
! pip install --upgrade numpy

  Using cached numpy-1.20.3-cp38-cp38-win_amd64.whl (13.7 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2


ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow 2.4.1 requires numpy~=1.19.2, but you'll have numpy 1.20.3 which is incompatible.


In [3]:
! pip install --use-feature=2020-resolver numpy


In [4]:
! pip install numpy==1.19.2

  Using cached numpy-1.19.2-cp38-cp38-win_amd64.whl (13.0 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3


## Utilizando o Numpy

In [5]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(3,)

In [9]:
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.shape

(2, 3)

In [11]:
print(f'Número de linhas: {np.size(b,0)}')
print(f'Número de colunas: {np.size(b,1)}')
print(f'Total de elementos: {np.size(b)}')

Número de linhas: 2
Número de colunas: 3
Total de elementos: 6


### Algumas funções do numpy

In [12]:
print(np.pi)

3.141592653589793


In [13]:
np.log(10)

2.302585092994046

In [14]:
np.log10(10)

1.0

In [15]:
np.exp(-3)

0.049787068367863944

In [16]:
a = np.array([-2, -1, 0, 1, 2])
print(np.exp(a))

[0.13533528 0.36787944 1.         2.71828183 7.3890561 ]


In [17]:
np.cos(np.pi/2)

6.123233995736766e-17

In [18]:
np.sin(30*np.pi/180)

0.49999999999999994

In [19]:
np.arccos(-0.5)

2.0943951023931957

In [20]:
np.arctan(0.8)*180/np.pi

38.659808254090095

In [21]:
np.sqrt(45)

6.708203932499369

### Manipulação de matrizes

In [22]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
b = np.ones((1,3,5))
b

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [24]:
c = np.full((3,2), 10)
c

array([[10, 10],
       [10, 10],
       [10, 10]])

In [25]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
e = np.random.rand(2,3)
e

array([[0.71809206, 0.66532789, 0.97717206],
       [0.53052712, 0.8782314 , 0.39046748]])

In [27]:
f = np.linspace(0, 3, 20)
f

array([0.        , 0.15789474, 0.31578947, 0.47368421, 0.63157895,
       0.78947368, 0.94736842, 1.10526316, 1.26315789, 1.42105263,
       1.57894737, 1.73684211, 1.89473684, 2.05263158, 2.21052632,
       2.36842105, 2.52631579, 2.68421053, 2.84210526, 3.        ])

In [28]:
g = np.logspace(-2, 2, 5)
g

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [29]:
h = np.arange(3, 7)
h

array([3, 4, 5, 6])

In [30]:
print(f'Dimensões de e {e.shape}')
i = np.reshape(e, (6,))
print(i)
print(f'Dimensões de i {i.shape}')

Dimensões de e (2, 3)
[0.71809206 0.66532789 0.97717206 0.53052712 0.8782314  0.39046748]
Dimensões de i (6,)


In [31]:
e.flatten()

array([0.71809206, 0.66532789, 0.97717206, 0.53052712, 0.8782314 ,
       0.39046748])

In [32]:
print(e)
print()
print(e.T)

[[0.71809206 0.66532789 0.97717206]
 [0.53052712 0.8782314  0.39046748]]

[[0.71809206 0.53052712]
 [0.66532789 0.8782314 ]
 [0.97717206 0.39046748]]


### Operações matemáticas básicas

In [33]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[3, 2, 1], [1, 1, 1], [6, 5, 8]])

In [34]:
a+b

array([[ 4,  4,  4],
       [ 5,  6,  7],
       [13, 13, 17]])

In [35]:
a-b

array([[-2,  0,  2],
       [ 3,  4,  5],
       [ 1,  3,  1]])

In [36]:
a*b

array([[ 3,  4,  3],
       [ 4,  5,  6],
       [42, 40, 72]])

In [37]:
a/b

array([[0.33333333, 1.        , 3.        ],
       [4.        , 5.        , 6.        ],
       [1.16666667, 1.6       , 1.125     ]])

In [38]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### Endereçamento de dados (Array slicing)

In [39]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [40]:
a[0,2]

3

In [41]:
b = np.array([[[1, 2], [3,4]],[[5, 6], [7,8]]])

In [42]:
b[1,1,1]

8

In [43]:
a[:,1]

array([ 2,  5,  8, 11])

In [44]:
a[2,:]

array([7, 8, 9])

In [45]:
b[:,:,1]

array([[2, 4],
       [6, 8]])

In [46]:
a[0, 1:4]

array([2, 3])

Endereçamento com booleanos

In [47]:
indice = a>5

In [48]:
indice

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [49]:
a[indice]

array([ 6,  7,  8,  9, 10, 11, 12])

In [50]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])